### ISSUE TITLE
纯交流贴，无实际错误

### ISSUE THREAD

**Issue by strongerw** [Mikachu2333/sc_starter#4]
作者你好，从知乎过来的，我花了点时间看了一下这个代码，我想知道这个软件的应用场景是什么样的，我记得市面上有类似功能的软件，或许你可以多了解一下，如果是单纯地出于兴趣那当我没说

**Comment by Mikachu2333** [comment]
应用场景：
1. 出于**保密需求**（例如学校的期末考题，非高密级的极其严肃的需求），要求在电脑中除已采购的软件及获批的部分软件（如被网站白名单限制的 IE 和 Firefox）以外，不允许存在非开源软件及其他可联网软件（所有包含联网功能的软件都需要写详细申请并做保证，纯开源软件不联网软件只需要写个简单申请即可）
2. 该电脑需要用于日常办公，且有频繁的截图需求
3. 截图仅需要**最基本的标注功能**（画框、加文字、加箭头）
4. 那台电脑很旧（Win7），储存空间也很小，所以排除所有Electron框架的软件，所需软件**体积尽可能小**

---

综合以上需求，而我不希望为了这么一个简单的小需求就搞一个成熟但体积巨大且附带一堆我不需要功能的软件（例如经典的 ShareX）。而原始软件 ScreenCapture 无常规用户页面，也不支持快捷键调用，只能通过点击的方式运行，但是它的优点完美符合我的需求：小、基本功能具备，只是缺少了一个快捷键唤起以提高效率的功能罢了。

因此，我的软件相当于给它进行了封装，向用户提供了快捷键功能而无须手动通过命令行操作程序（算个变异版的gui了）。而本软件开源，引用的软件及相关组件均为开源，且均为 MIT Licence，无任何可能的风险（也无须因此写报告……）

---

如果有其他能满足需求的软件欢迎告知，我这软件极不成熟，错误处理没有、配置过于繁琐、没法指定内置文件的释放目录、不能检测是否为便携版、设置文件的读取一坨狗屎（为了不额外添加依赖故意的，但是还有极大的优化空间）等等诸多问题，但因为我是非软件工程专业出身（医学生），由于能力所限我也很难进一步完善代码……所以如果您能满足上述需求的软件欢迎告知！我会高兴地对本软件停止维护然后转投更加完善的软件（
